name: avalon-nginx-reverse-proxy

networks:
  avalon-reverse-proxy-net:
    external: true

services:
  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - avalon-reverse-proxy-net
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot-ssl
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh
    networks:
      - avalon-reverse-proxy-net
    command: -c "trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew --webroot -w /var/www/certbot; done"