name: avalon-portainer

networks:
  avalon-reverse-proxy-net:
    external: true

services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: always
    networks:
      - avalon-reverse-proxy-net
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: